export const brandTokens = {
  colors: {
    primary: '#ec5b13',
    primaryHover: '#d44e0f',
    teal: '#2aa7a2',
    tealHover: '#228f8a',
    tealLight: '#e6f7f6',
    background: '#f8f6f6',
    surface: '#ffffff',
    ink: '#0f172a',
    subtle: '#334155',
    muted: '#64748b',
    border: '#e2e8f0',
    borderWarm: '#f1d8cd',
  },
  typography: {
    fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, sans-serif',
    sizes: {
      xs: 10,
      sm: 12,
      base: 14,
      md: 15,
      lg: 17,
      xl: 20,
      '2xl': 24,
      '3xl': 28,
    },
    weights: {
      regular: '400' as const,
      medium: '500' as const,
      semibold: '600' as const,
      bold: '700' as const,
      extrabold: '800' as const,
    },
    lineHeights: {
      tight: 1.2,
      snug: 1.4,
      normal: 1.6,
    },
  },
  radii: {
    sm: 4,
    control: 8,
    card: 12,
    pill: 16,
    cta: 24,
    full: 9999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    base: 16,
    lg: 20,
    xl: 24,
    '2xl': 32,
  },
  shadows: {
    card: {
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    cta: {
      shadowColor: '#ec5b13',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 12,
      elevation: 6,
    },
  },
} as const;

export type BrandTokens = typeof brandTokens;
